### PR TITLE
add canonical link support

### PR DESCRIPTION
**Pull request by Darival**
Add Canonical Link field seo create & edit modals.

[What is a Canonical URL?](https://blog.alexa.com/canonical-url/
)

> When You Repost Existing Content
If you have a website that is a part of a franchise or national organization, then you may share statements, press releases, and even blog content originally published on the main national website. Instead of merely linking to the original content and hoping site visitors click through, you may publish the content on your own site. This is duplicate content that needs a canonical tag. You can use a canonical URL to direct search crawlers to the original post so that it doesn’t look like you are copying the page.

this still needs a way to prevent "Undefined index: canonical_link" when trying to edit a post created before this field existed.

### CODE REVIEW

**Comment by Darival** [comment]
need help validating lang files, i only speak spanis and enlish, google translated the rest.

**Comment by Darival** [comment]
Canonical_link is stored in the json 'meta' column, alongside og and twitter, so a migration is not required.

I can just @if() @endif the canonical tag to avoid "Undefined index: canonical_link".

And now that i think about it, this needs to be added anyways because there should not be an empty canonical href, that could be bad for the seo.

**Comment by austintoddj** [comment]
Ah you're right, didn't see that it was bundled with the meta. Nice work on that.

Go ahead and push up any more changes and I'll take another look.

**Comment by Darival** [comment]
Sure, i'll and the @if

**Comment by Darival** [comment]
Hi @austintoddj,
I think that's it.
I just dont know if the translations are good enough.

**Pull request merged**
