### PR TITLE
Fix file and directory permissions

### PR DESCRIPTION
**Pull request by ruchern**
For some reason, when I clone this repo, all the files are at `755`. 

Just following some standards, files should be `644` while directories are `755`.

### CODE REVIEW

**Comment by austintoddj** [comment]
Thanks for submitting this @ruchern. File permissions are something I've been trying to get permanently fixed for Canvas, and this may very well be the first step in the right direction.

The biggest issue Canvas faces is the fact that directories like `public/vendor/` need to be writable by both the web server and the command line Linux user. In a safe fashion, like not trying to use `chmod 777` on these files, I can't figure out a good way to document this so that people will be able to change themes from the app UI, while also run commands like `canvas:update`. They collide because of permissions. Any thoughts on this?

**Comment by ruchern** [comment]
@austintoddj Regarding your concerns with the `public/vendor/` directory, the Linux user has to set the `group` to `www-data` rather than their own username. One way you could do while doing the install/update is to run `chgrp -R www-data *` This is indeed a problem between development and deployment platform.

**Comment by austintoddj** [comment]
Thanks @reliq! And thank you @ruchern for the PR!

**Comment by ruchern** [comment]
Thank you @reliq and @austintoddj for the merge!

**Pull request merged**
