### PR TITLE
Add EU cookie disclaimer package

### LINKED ISSUE #173: Add EU Cookie Disclaimer
http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm

### PR DESCRIPTION
**Pull request by Jeroen-G**
Set the `COOKIE_CONSENT_ENABLED` flag in .env to true and it should appear. The flag defaults to false for now, I suppose the EU law requires _every_ site dealing with data from EU citizens to show the message. But that is up to someone else to figure out 😄 

Fixes #173

### CODE REVIEW

**Comment by Jeroen-G** [comment]
Travis failed, is this because of the package?

**Comment by austintoddj** [comment]
@Jeroen-G Hm odd. Let me look into it and see what I can find out.

**Comment by Jeroen-G** [comment]
It works locally by the way.

**Comment by austintoddj** [comment]
With the core of Canvas refactored out to Easel, I think #177 is far more viable in the near future, and a PR like this could change into a Canvas-related package that is integrated. Going to close this out for now.

@Jeroen-G If you want to take a stab at creating a package that can be plugged into Canvas, by all means go ahead.

**Pull request closed without merging**
